# Configuration for the cinematic dataset scraper

# Keywords for searching cinematic videos on YouTube
keywords:
  - 'action scene'
  - 'neon city'

# Scraper settings
# A list of scraper strategies to use. Currently available: 'youtube'
active_scrapers:
  - youtube

scraper:
  search_prefix: 'ytsearch3' # Search for 10 videos for each keyword
  download_limit_per_keyword: 2 # Limit of videos to download for each keyword to avoid too many requests
  max_video_duration: 900 # Maximum duration in seconds (15 minutes) to consider for download

# Processing settings
processing:
  clip_duration: 5  # seconds
  min_clip_duration: 1 # seconds

# Paths
paths:
  dataset_dir: 'dataset'
  raw_videos_dir: 'temp/raw_videos'
  logs_dir: 'logs'
  hashes_file: 'temp/processed_hashes.txt'
  index_file: 'dataset/index.csv'
  report_file: 'report.md'
